import '@assets/styles/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import {Header, Footer } from "@components"


const inter = Poppins({ subsets: ['latin'], weight: "400"})

export const metadata: Metadata = {
  title:{
    default: "MyPage - Daniel Renato",
    template: "MyPage | %s" 
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={`dark:text-white dark:bg-slate-900 ${inter.className}`}>
        <Header />
        {children}
        </main>
      
        
        </body>
    
    </html>
  )
}
